spring:
  datasource:
    url: jdbc:mysql://192.168.23.123:32722/urban_management_platform?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver