spring:
  datasource:
    url: jdbc:mysql://192.168.23.123:32722/urban_management_platform?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30              # 最大连接数
      minimum-idle: 10                   # 最小空闲连接
      connection-test-query: SELECT 1    # 连接测试查询
      connection-timeout: 60000          # 连接超时时间 毫秒
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true


  activiti:
    history-level: full
    check-process-definitions: false
    db-history-used: true
    use-strong-uuids: true