@startuml
title 城管类图
class User <<用户实体类>>{
    -id: String
    -name : String
    -sts : int
}

class Dept<<责任部门实体类>>{
    -id: String
    -deptName : String
    -sts : int
    -level : String
    -parent : Dept
    -userList : User[*]
}

class Grid<<网格实体类>>{
    -id: String
    -gridCode : String
    -gridName : String
    -remark : String
    -kv : Kv    //代表所属区域
    -area : String
    -initialDate : date
    -terminationDate : date
    -sts : int
    -dept : Dept
    -user : User
    -release : Release
    -record : Record
    -publish : Publish
}

class Component<<部件实体类>>{
    -id: String
    -eventType : EventType
    -componentInfo : ComponentInfo
    -sts : int  // 用于记录该部件删除
    -publish : Publish
    -record : Record
}


class ComponentInfo<<部件信息实体类>>{
    -id : String
    -objId : String
    -objName : String
    -mainDeptCode : String
    -mainDept : String
    -ownershipDeptCode : String
    -ownershipDeptName : String
    -maintenanceDeptCode : String
    -maintenanceDeptName  : String
    -bgid : Grid
    -objState : Kv
    -initialDate : date
    -changeDate : date
    -dataSource : Kv
    -note : String
}

class Publish<<发布实体类>>{
    -id : String
    -name : String
    -layerId : String     //图层ID:当发布后GIS平台将把该图层ID返回城管中，城管再次添加元素可以找到对应GIS平台的哪个图层
    -url : String         //GIS平台提供的发布的图层地址
    -kv : Kv              //类型：编辑的是部件、网格。
    -sts : int            //状态：用于判断是发布、未发布状态
    -user : User          //用于记录谁发布的
    -eventType : EventType
}
class Record<<编辑实体类>>{
    -id : String
    -coordinate : String  //坐标
    -user : User
    -publish : Publish
    -sts : int //判断该记录是编辑中、发布
}

class Kv<<Kv实体类>>{
    -id : String
    -tableName : String
    -fieldName : String
    -value : String
    -sts : int
}

class Event<<案件实体类>>{
    -id : String
    -eventCode : String
    -eventTypeId : EventType     //分类id
    -represent : String
    -gridId : Grid
    -location : String
    -User : User
    -phone : String
    -eventSource : Kv
    -x : double
    -y : double
    -taskId : String
    -timeLimit : TimeLimit
    -sts       : int             // 事件状态     派遣/挂起等等
    -recTypeId : Kv       //案件类型    日常  、转向普查、其他
    -region : Kv    //区域    一类区域  二类区域  三类区域
    -eventSate : Kv  // 案件状态
    -eventCondition : EventCondition
}

class EventType<<分类实体类>>{
    -id   : String
    -type : int
    -code : String
    -name : String
    -level : int 
    -parentId : String
}

class EventFile<<事件附件实体类>>{
    -id : String
    -fileName : String
    -eventId : Event
    -fileType ：int
}
class EventCondition<<立案条件实体类>>{
    -id : String
    -conditionValue : String
    -eventTypeId : EventType
}

class DeptTimeLimit<<专业部门时限实体类>>{
    -id : String
    -eventTypeId : EventType
    -level : Kv
    -timeLimit : int     //时限
}

class ProcessTimeLimit<<流程时限实体类>>{
    -id : String
    -taskName : String
    -level : Kv
    -timeLimit : int     //时限
}

class EventPhase<<流转记录实体类>>{
    -id : String
    -eventId : Event
    -userId : User
    -taskId : String             //流程图实例id  (步骤)
    -taskName : String           //流程名
    -opinions : String           //处理意见
    -eventFileId : EventFile     //附件
    -starTime : date
    -endTime  : date
    -deptTimeLimit  :  DeptTimeLimit
    -processTimeLimit  :  ProcessTimeLimit
}

class EventTime<<案件时间记录实体类>>{
    -id : String
    -eventId : Event
    -creatTime : Date           //上报时间
    -operateTime : Date         //受理时间
    -instTime : Date            //立案时间
    -dispatchTime : Date        //派遣时间
    -archiveTime : Date         //结案时间
    -cancelTime : Date          //作废时间
    -sendVerifyTime : Date      //发核实时间
    -sendCheckTime : Date       //发核查时间
    -verifyTime  : Date         //核实时间
    -checkTime : Date           //核查时间
    -disposeBeginTime : Date    //处置开始时间
    -disposeDeadline : Date     //处置截至时间
    -disposeEndTime : Date      //处置结束时间
    -superviseTime : Date       //督查时间
}

class ReportStatistics<<上报统计>>{
    -id                   : String
    -userId               : User
    -patrolReport	      : int       //监督员上报
    -publicReport	      : int       //公众举报
    -report			      : int       //上报
    -reportPatrolId	      : int       //上报监督员标识
    -reportPatrolName	  : String    //上报监督员
    -validPatrolReport    : int       //监督员有效上报
    -validPublicReport    : int       //公众举报有效上报
    -validReport		  : int       //有效上报
}

class VerifyStatistics<<核实统计>>{
    -id                     : String
    -userId                 : User
    -needSendVerify         : int          //应发核实               
    -sendVerify             : int          //发核实
    -intimeSendVerify       : int          //按时发核实
    -needVerify             : int          //应核实
    -verify                 : int          //核实
    -intimeVerify           : int          //按期核实
    -sendVerifyHumanId      : int          //发核实人标识
    -sendVerifyHumanName    : String       //发核实人
    -sendVerifyHumanRoleId  : int          //发核实人岗位标识
    -verifyPatrolId         : int          //核实监督员标识
    -verifyPatrolName       : String       //核实监督员
}

class AcceptanceStatistics<<受理统计>>{
    -id               : String
    -userId           : User
    -notOperate       : int     //不予受理
    -toOperate        : int     //待受理
    -intimeOperate    : int     //按时受理
    -operate          : int     //受理
    -operateHumanId   : int     //受理人标识
    -operateHumanName : String  //受理人
    -operateRoleId    : int     //受理人岗位标识

}
class CaseStatistics<<立案统计>>{
    -id             : String
    -userId         : User
    -inst           :  int      //立案
    -intimeInst     :  int      //按时立案
    -toInst         :  int      //待立案
    -notInst        :  int      //不予立案
    -instHumanId    :  int      //立案人标识
    -instHumanName  :  String   //立案人
    -instRoleId     :  int      //立案人岗位标识
}
class DispatchStatistics<<派遣统计>>{
    -id                   : String
    -userId               : User
    -dispatch             : int      //派遣         
    -toDispatch           : int      //待派遣       
    -needDispatch         : int      //应派遣       
    -intimeDispatch       : int      //按时派遣     
    -dispatchHumanId      : int      //派遣员标识     
    -dispatchHumanName    : String   //派遣员         
    -dispatchHumanRoleId  : int      //派遣员岗位标识 
}
class DisposalStatistics<<处置统计>>{
    -id                   : String
    -userId               : User
    -dispose              : int      //处置         
    -needDispose          : int      //应处置       
    -intimeDispose        : int      //按时处置     
    -overtimeToDispose    : int      //超时未处置   
    -overtimeDispose      : int      //超时处置     
    -toDispose            : int      //未处置       
    -disposeOpinion       : text     //处置意见       
    -disposeUnitId        : int      //处置部门标识   
    -disposeUnitName      : String   //处置部门   
}
class InspectionStatistics<<督查统计>>{
    -id                    : String
    -userId                : User
    -intimeSupervise       : int      //按时督查   	
    -needSupervise         : int      //应督查   		
    -supervise             : int      //督查    		
    -toSupervise           : int      //待督查   		
    -superviseHumanId      : int      //督查人标识   	
    -superviseHumanName    : String   //督查人    		
    -superviseHumanRoleId  : int      //督查人岗位标识  
}
class VerificationStatistics<<核查统计>>{
    -id                    : String
    -userId                : User
    -check                 : int      //核查            
    -needCheck             : int      //应核查          
    -intimeCheck           : int      //按时核查        
    -intimeSendCheck       : int      //按时发核查      
    -sendCheck             : int      //发核查          
    -needSendCheck         : int      //应发核查        
    -checkTrans            : int      //核查批转        
    -checkPatrolId         : int      //核查监督员标识    
    -checkPatrolName       : String   //核查监督员        
    -checkTransHumanId     : int      //核查受理员标识    
    -checkTransHumanName   : String   //核查受理员        
    -checkTransHumanRoleId : int      //核查受理员岗位标识
    -checkTransTime        : datet    //核查批转时间      
    -sendCheckHumanId      : int      //发核查人标识      
    -sendCheckHumanName    : int      //发核查人          
    -sendCheckHumanRoleId  : int      //发核查人岗位标识  
}
class ClosingStatistics<<结案统计>>{
    -id                  : String
    -userId              : User
    -archive             : int      //结案          
    -humanArchive        : int      //值班长结案    
    -intimeHumanArchive  : int      //值班长按时结案
    -needHumanArchive    : int      //值班长应结案  
    -intimeArchive       : int      //按期结案      
    -intimeToArchive     : int      //按期未结案    
    -needArchive         : int      //应结案        
    -overtimeArchive     : int      //超期结案      
    -overtimeToArchive   : int      //超期未结案    
    -toArchive           : int      //未结案        
    -archiveHumanId      : int      //结案人标识      
    -archiveHumanName    : String   //结案人          
    -archiveHumanRoleId  : int      //结案人岗位标识  

}
class VoidStatistics<<作废统计>>{
    -id             :  String
    -userId         :  User
    -cancel         :  int       //作废       
    -cancelOpinion  :  text      //作废意见     
    -hang           :  int       //挂账       
    -hisHang        :  int       //历史挂账   
    -postpone       :  int       //延期       
    -rework         :  int       //返工       
    -multiRework    :  int       //返工次     
    -displayStyleId :  int       //显示类型标识 
    -shuffle        :  int       //推诿       
}

   












class ComponentController<<部件界面类>>{
    -ComponentService
    -ComponentInfoService
    +ComponentList(component):Component[*]         // 查询部件集合
    +saveComponentList(Component[*]):boolean       // 保存部件
    +componentImport():boolean
    +objState() : Kv[*]
    +dataSource() : Kv[*]
    +grid() : Grid[*]
    +record(ComponentType): Record[*]
    +componentByRecordId(record) : Component[*]
}

class ComponentService<<部件业务类>>{
    -ComponentInfoService
    +getComponentList(component):Component[*]      // 查询部件集合
    +getComponent(component) :component
    +saveComponentList(component[*]): boolean
    +saveComponent(component) : boolean
    +savePublish(publis) : boolean
    +saveRecord(record,publish) : boolean
    +getComponentByRecordId(record) : Component[*]
    +deleteComponent(component) : boolean
}
class ComponentTypeService<<部件分类业务类>>{
    +getComponentTypeList():ComponentType[*]       // 获取部件分类集合
    +getComponentType(component):ComponentType     // 获取部件分类
}

class PublisheController<<发布界面类>>{
    +getPublishList() : Publish[*]
    +getPublishOne() : Publish
    +layerPublish(publish) : boolean
}
class PublisheService<<发布业务类>>{
    +getPublishList() : Publish[*]
    +getPublishOne() : Publish
    +layerPublish(publish) : boolean
}

class RecordService<<编辑业务类>>{
    +save(record) : boolean
    +update(record) : boolean
    +findAllByPublishId() : Record[*]
}
class ImportController<<导入界面类>>{
    +componentImport(layerName,layerSettingType,shpType) : String
    +gridImport(layerName,layerSettingType,shpType) : String
    +checkPublish(): boolean
}
class ImportService<<导入业务类>>{
    +componentImport(layerName,layerSettingType,shpType) : String
    +gridImport(layerName,layerSettingType,shpType) : String
    +checkPublish(): boolean
}

class GridController<<网格界面类>>{
    +getGridList() :  Grid[*]
    +gridSave(grid) : boolean
    +gridUpdate(grid) : boolean
    +getGridOne(grid) : Grid
    +gridDelete(grid) : boolean
}

class GridService<<网格业务类>>{
    +search(grid) : Grid[*]
    +delete(grid) : boolean
    +update(grid) : boolean

}






Dept --> User
Grid --> User
Grid --> Dept
Grid --> Record
Grid --> Publish
Grid --|> Kv
Component --> ComponentInfo
Component --> Record
Component --> Publish
ComponentInfo --|> Kv
Publish --> Record
Publish --|> Kv
Event --> EventType
EventCondition -->  EventType 
Event --|> Kv
Event --|> EventTime
Event --|> EventPhase
EventType -->  DeptTimeLimit
EventPhase --> DeptTimeLimit 
EventPhase --> ProcessTimeLimit 
EventPhase --> EventFile
ReportStatistics --> User
VerifyStatistics --> User
AcceptanceStatistics --> User
CaseStatistics --> User
DispatchStatistics --> User
DisposalStatistics --> User
InspectionStatistics --> User
VerificationStatistics --> User
ClosingStatistics --> User
VoidStatistics --> User






' ComponentController --> ComponentService
' PublisheController --> PublisheService
' ImportController --> ImportService
' GridController --> GridService


' GridService --> RecordService
' GridService --> KVService
' GridService --> UserService
' PublishService --> RecordService
' PublishService --> GridService
' ComponentService --> PublishService
' ComponentService --> RecordService



' ComponentService ..> Component
' PublisheService ..> Publish
' RecordService ..> Record




@enduml